### ISSUE TITLE
BUG: error on token name when visiting contract page

### ISSUE THREAD

**Issue by FidelVe** [sudoblockio/icon-tracker-frontend#111]
The following issue is happening on the lisbon tracker. when you visit the following [contract page](https://tracker.lisbon.icon.community/contract/cxcadcaf77d8e46089fd3d98fcf71eabee1700f148#readcontract) it displays that the token name is `btp-0x2.icon-sICX` when the actual name for the token is `btp-0x2.icon-bnUSD`

![photo_2023-01-08_21-50-17](https://user-images.githubusercontent.com/43641727/211230064-11c3f560-77df-4528-a2e7-407a6ab08aba.jpg)

**Comment by robcxyz** [comment]
@FidelVe - Thanks for posting issue 

This is very strange though as I am seeing correct token name. 

![image](https://user-images.githubusercontent.com/6512972/211469554-8fed5a1c-6531-4146-b338-4a3d864de574.png)

This is still an issue though. Can you get in touch with me to do a screen share or show me the actual responses if you see this issue again? This should never happen and perhaps comes from some page reloading issue?

**Comment by FidelVe** [comment]
Hi Rob. I'll Dm you on telegram 👍

**Comment by robcxyz** [comment]
I think this is cloudflare caching. Will close this for now but this still should never happen. Calling it caching is sort of a cheap excuse but all I have....
