### ISSUE TITLE
Feature Request: Add method name in wallet page too for transactions

### ISSUE THREAD

**Issue by ajaya-man** [sudoblockio/icon-tracker-frontend#112]
In contract page, there is a method column which is very helpful.
<img width="1244" alt="image" src="https://user-images.githubusercontent.com/16894496/211366468-00427731-d866-4cd5-b248-43540422966e.png">

It would be helpful if the method column were added to the wallet page.

<img width="1323" alt="image" src="https://user-images.githubusercontent.com/16894496/211366836-bdcd6fc5-a8cd-4c2f-851e-fd8f4b7a718b.png">

**Comment by robcxyz** [comment]
@athoifss - /addresses page like this https://tracker.icon.community/address/hx412d1f88f54b86b9265827b943700ed14c8121f3
