### ISSUE TITLE
BUG: Token percentage shown is wrong

### ISSUE THREAD

**Issue by ajaya-man** [sudoblockio/icon-tracker-frontend#113]
![image](https://user-images.githubusercontent.com/16894496/211367230-1afe14a9-1deb-4db9-a51e-6a1d42161865.png)

The quantity and token percentage are wrong for the token. Quantity should add more decimals.

**Comment by robcxyz** [comment]
@athoifss - This is a rounding error most likely on your side as no rounding is done on the backend. Can you check if you are using integers for the balance of these wallets?

Link
https://tracker.icon.community/token/cx5b5a03cb525a1845d0af3a872d525b18a810acb0#tokenholders

Balance endpoint
https://tracker.icon.community/api/v1/transactions/token-holders/token-contract/cx5b5a03cb525a1845d0af3a872d525b18a810acb0?contractAddr=cx5b5a03cb525a1845d0af3a872d525b18a810acb0&limit=10

Looks like balance is caste as int
