### ISSUE TITLE
BUG: Amount of IUSDC shown is wrong

### ISSUE THREAD

**Issue by ajaya-man** [sudoblockio/icon-tracker-frontend#125]
https://tracker.icon.community/address/hx32d42a1f4eb64f3c1ddb8badfe45b45c59fde647

For this address, the number of iusdc tokens shown is wrong in the token transfer section. When I click on an individual transaction, it's okay though. I guess it must be due to the assumption that every token has 18 decimals. USDC has only 6 decimals, thus giving incorrect values.

**Comment by ajaya-man** [comment]
For reference, you can check the page of 
https://main.tracker.solidwallet.io/address/hx32d42a1f4eb64f3c1ddb8badfe45b45c59fde647

You can find the differences in number as well as internal transactions is also not shown.

**Comment by robcxyz** [comment]
@athoifss - Looks like the API is returning the right value. Looking at the second token transfer, the response is 3900 for the `value` yet in the FE it shows 0.

**Comment by ajaya-man** [comment]
Duplicate of Issue https://github.com/sudoblockio/icon-tracker-frontend/issues/2
