### ISSUE TITLE
Internal transactions tab not working properly

### ISSUE THREAD

**Issue by Geograd** [sudoblockio/icon-tracker-frontend#146]
Community Tracker: https://tracker.icon.community/address/hx7727d7b3fcc964d703a0b1a5a1c0e70e00000000

ICON Tracker: https://main.tracker.solidwallet.io/address/hx7727d7b3fcc964d703a0b1a5a1c0e70e00000000#tokentransfers

**Comment by robcxyz** [comment]
And different count (23 vs 21)
