### ISSUE TITLE
Detailed debug trace on failed Txs pop up 

### ISSUE THREAD

**Issue by robcxyz** [sudoblockio/icon-tracker-frontend#17]
Integrate https://github.com/Prajeet-Shrestha/icon-tx-tracer-debugger into the tracker as a pop up for failed Txs.  Would basically be a pop up version of https://icon-tx-tracer.vercel.app/ triggered from a link within the tracker. 

This will need some interim checkins to get right as it gets built.

**Comment by robcxyz** [comment]
Using above links (vercel app and source), embed the side progress / lines / dots on to the side of the view with the right CSS color scheme. Ignore the top bar with the "Tx Hash" box and "Trace" Button. Also no need for network selector (ie Berlin / Mainnet / etc). Instead of "Transaction" header, show "Debug Trace". 

Example failed Tx: https://tracker.icon.community/transaction/0x8fd21364557c8f75fde511f1e56322f1a67265e7c6c8b9997f644eacdb15de90
New endpoint: https://tracker.icon.community/transaction/trace/0x8fd21364557c8f75fde511f1e56322f1a67265e7c6c8b9997f644eacdb15de90
**Notice the */trace/{tx hash}**

**Comment by ajaya-man** [comment]
Can you make the trace a tree that can be collapsed based on the frame number?
We should be able to collapse and expand each frame as per requirement. Frames are nested inside each other.

Example:
If FRAME[3] could be collapsed as it is under frame 2. So basically able to close child frames. 

In close stage, we could see something like

FRAME[1]
 &nbsp;&nbsp;&nbsp;&nbsp;[+] FRAME[2]
 &nbsp;&nbsp;&nbsp;&nbsp; &nbsp;&nbsp;&nbsp;&nbsp;[+] FRAME[3]
 &nbsp;&nbsp;&nbsp;&nbsp; &nbsp;&nbsp;&nbsp;&nbsp;[+]FRAME[4]
 
 Where clicking on + symbol would expand the FRAME.
 
<img width="1237" alt="image" src="https://user-images.githubusercontent.com/16894496/177528337-e1b2f4cb-9230-4617-84fb-39e581e51642.png">
