### ISSUE TITLE
Fix pagination on transaction list pages 

### ISSUE THREAD

**Issue by robcxyz** [sudoblockio/icon-tracker-frontend#18]
Comparing 

- https://tracker.v2.mainnet.sng.vultr.icon.community/contracttx/cx9ab3078e72c8d9017194d17b34b1a47b661945ca/48?count=25
  - 48 pages 
  - Runs -> https://tracker.v2.mainnet.sng.vultr.icon.community/api/v1/transactions/address/cx9ab3078e72c8d9017194d17b34b1a47b661945ca?addr=cx9ab3078e72c8d9017194d17b34b1a47b661945ca&limit=25&skip=1175
- https://tracker.icon.foundation/contracttx/cx9ab3078e72c8d9017194d17b34b1a47b661945ca/49?count=25
  - 49 pages 

There should be 49 pages in the first response. When looking at the x-total-count header which informs the paging, we have 1222 which should produce 1222 / 25 = 48.8 pages (49 pages as we always round up)

Also happens in `/addresstx` endpoint -> 

- https://tracker.v2.mainnet.sng.vultr.icon.community/addresstx/hx562dc1e2c7897432c298115bc7fbcc3b9d5df294/720?count=25
- https://tracker.icon.foundation/addresstx/hx562dc1e2c7897432c298115bc7fbcc3b9d5df294/721?count=25

Also `/blocktx` -> 
- https://tracker.icon.foundation/blocktx/31670491
- https://tracker.v2.mainnet.ams.vultr.icon.community/blocktx/31670491/10?count=25

Also happens in token transfers though backend is broken and will be fixed shortly for this.  If can fix, do it as problem should be the same for all. 

Last, this happens in `blocktx` but

**Comment by Fasunle** [comment]
Hi 👋,

Do you know if that is not a backend bug? The roundup could have been done from the backend.

**Comment by robcxyz** [comment]
@Fasunle - No this is a frontend issue. Pagination is done based on x-total-count header which has been QCed.  Thanks for suggestion though. This will hopefully be closed in a day or two.
