### ISSUE TITLE
List of types of proposals along with their schema for value 

### ISSUE THREAD

**Issue by robcxyz** [sudoblockio/icon-tracker-frontend#190]
Per title, in building out the proposal submission page, we need a list of types of proposals and what their `value` field would look like. 

Add list to notion here -> https://www.notion.so/sudoblock/Proposal-Types-cc4b0f3934d04e159dca38cfdab8d114

**Comment by FidelVe** [comment]
Done

**Comment by FidelVe** [comment]
@robcxyz im closing this one as it is already completed on notion.
