### ISSUE TITLE
EPIC: Contract Write Meta 

### ISSUE THREAD

**Issue by robcxyz** [sudoblockio/icon-tracker-frontend#193]
Meta issue for [transaction write proposal](https://www.notion.so/sudoblock/Transaction-Write-188d8e2b7350472197e990c506531079)

## Design 
- [x] #190 - @FidelVe
- [x] #192
- [x] #221
- [x] #222
- [x] #223

## Dev 

Fidel 
- [x] #61 
- [x] #101 
- [x] #102 
- [x] #224
- [x] #226
- [x] #194
- [x] #241
- [x] #242
- [x] #243
- [x] #244
- [ ] #245 

Atif 
- [ ] #219 - @athoifss 

#### CSS

- [ ] #197  - @athoifss 
- [ ] #195 - @athoifss 
- [ ] #196  - @athoifss 

Debug / trace 

- [ ] #214 - @athoifss 
- [ ] #17 - @athoifss 
- [ ] #154 - @athoifss 
- [ ] #64 - @athoifss 

#### Phase 2

- [x] #72
- [ ] #139
- [ ] #75

## Testing 

- [x] #191 
- [ ] #250 
- [x] #252

## Ops

- [ ] #227
- [ ] #248
- [x] #251

- @robcxyz 
- @FidelVe
- @athoifss 
- @thecomputerfella
- @harilee1325

**Comment by FidelVe** [comment]
@robcxyz is it possible for you to allow me to self assign myself to the ones im being tagged or for you to assign me to them so I can track all of this better?
https://stackoverflow.com/questions/26752902/how-to-assign-issue-to-myself-at-github

**Comment by robcxyz** [comment]
Bump
