### ISSUE TITLE
Bonded address opens in new tab 

### ISSUE THREAD

**Issue by robcxyz** [sudoblockio/icon-tracker-frontend#208]
https://tracker.v2.mainnet.sng.vultr.icon.community/address/hxf6df6b4cbe687c822e611fff727382b457ab6e82

Click on address and it should not open in a new tab

**Comment by FidelVe** [comment]
also happens when clicking on an address in the 'delegations tab' of the table
https://tracker.v2.mainnet.sng.vultr.icon.community/address/hxf6df6b4cbe687c822e611fff727382b457ab6e82
