### ISSUE TITLE
Enable search bar in contract and token list views 

### ISSUE THREAD

**Issue by robcxyz** [sudoblockio/icon-tracker-frontend#21]
Per title, we need to support a search bar in both the contract and token list views. This should be already implemented and just need to be enabled but with a new backend call. 

Currently the only thing to search on is `name` which should be part of the search. There is a query parameter `search` for the /addresses/contracts endpoint that should be filled in with the search bar. 

Swagger: https://tracker.icon.community/api/v1/docs/index.html#/Addresses/get_api_v1_addresses_contracts

Again, this functionality should already exist in the code and is just flagged out right now. Should not need to implement from scratch.

**Comment by Fasunle** [comment]
What contract name can I use to test the SwaggerUI docs?

**Comment by robcxyz** [comment]
@Fasunle - It is case insensitive / accepts partial contract names so `omm`, `balanced`, `bal` will all return results. It is all based on the contracts `Name` method but am open to suggestion to any other field to search on like symbol.
