### ISSUE TITLE
Modify `config.js` so that we can run locally on each network 

### ISSUE THREAD

**Issue by robcxyz** [sudoblockio/icon-tracker-frontend#219]
We need a way to run the tracker on multiple networks (ie mainnet vs testnets). Right now it selects two important inputs based on what the origin is in [config.js](https://github.com/sudoblockio/icon-tracker-frontend/blob/main/src/config.js#L4). We need a way to be able to run it easily locally via `npm start <options>` and / or environment variables. There are two key variables, the rpc endpoint and api endpoint. There should be an additional option for simply supplying the network which will then use the [current logic in the config.js](https://github.com/sudoblockio/icon-tracker-frontend/blob/main/src/config.js#L14) to select the network. 

## Options 

- `network`  - `ICON_NETWORK` env var 
  - mainnet (default if not supplied)
  - berlin
  - lisbon
  - sejong
  - custom

This should be exposed as an option `npm start --network mainnet` which will then choose 

For `custom` network, additionally expose 

- api_endpoint - `ICON_API_ENDPOINT`
  - This is only possible if you setup your own indexer. 
  - Most of the time this will not be the case in which case the majority of the tracker will represent the custom network (ie it will fallback on whatever api_endpoint is configured like mainnet 
  - For e2e testing contract write methods, this would be helpful 
- rpc_endpoint  - `ICON_RPC_ENDPOINT` 
- nid -  `ICON_NID`

**Comment by FidelVe** [comment]
I think there would issues with custom networks, the tracker frontend uses the api in the tracker backend for many call, not everything is done via RPC calls to nodes.

if we allow for a custom network there is no way to have the tracker backend api (rpc_endpoint) related to whatever custom network the uses defines as the api_endpoint which can be things like a local network or simply another endpoint on mainnet or any testnet.

**Comment by robcxyz** [comment]
Fair points but the only use case of the custom network is for testing at this point. To create API endpoints would require spinning up a backend which can be configured for a custom endpoint, albeit a bit involved. 

Not sure what you mean about  "no way to have the tracker backend api (rpc_endpoint)". There would be no API endpoints as mentioned but you would have RPC. I think you are mixing up API vs RPC, the latter of which a custom endpoint would have.

**Comment by FidelVe** [comment]
> Fair points but the only use case of the custom network is for testing at this point. To create API endpoints would require spinning up a backend which can be configured for a custom endpoint, albeit a bit involved.
> 
> Not sure what you mean about "no way to have the tracker backend api (rpc_endpoint)". There would be no API endpoints as mentioned but you would have RPC. I think you are mixing up API vs RPC, the latter of which a custom endpoint would have.

Yeah that was a typo it should have been "no way to have the tracker backend api (api_endpoint)" on a custom network

**Comment by robcxyz** [comment]
Well there is a way but you will need to run it. Over time we will try to make it easier but there is a docker compose to run your own indexer. Regardless, I think we try to make the contract r/w section not use the indexer if possible or if it does, then exclude any information from the custom network from this view. 

If using the API is helpful, then we only offer this for indexed networks which is going to be >95% of usage I think (could be wrong). 

For custom networks though, the main reason I was thinking we want to be able to configure this is for e2e testing of the non-contract r/w section calls. For the contract r/w, we are exposing that as an option but for other things like create proposal, it is not exposed. 

We still need to verify that we can make calls to a custom network's governance contract and what steps we need to implement to get that going.
