### ISSUE TITLE
Header Data caches and does not refresh when using the magnifier search feature

### ISSUE THREAD

**Issue by Geograd** [sudoblockio/icon-tracker-frontend#225]
Go to any contract on the tracker and then use quick search to go to another contract and the data at the top will not refresh.

**Comment by robcxyz** [comment]
Example: https://tracker.icon.community/contract/cx21e94c08c03daee80c25d8ee3ea22a20786ec231#internaltransactions

Click on another contract from the internal transactions list and the header is the same
