### ISSUE TITLE
Tx trace logsfor failed txs doesn't work - no error msg

### ISSUE THREAD

**Issue by VagPanour** [sudoblockio/icon-tracker-frontend#299]
Example
https://tracker.icon.community/transaction/trace/0xc55fa2b89b0079584267f0111fdc832637438440b4441ab03c8959fdcd97e95a
![1](https://github.com/sudoblockio/icon-tracker-frontend/assets/93825444/a514ffb9-48af-4589-ba68-f13888d97bfd)

**Comment by robcxyz** [comment]
Hmm odd. Works for me now. Can you verify? If it is broken can you include any info about  what API call was failing?

**Comment by VagPanour** [comment]
Example of a failed tx.
https://tracker.icon.community/transaction/trace/0x92684cfc4bca9e7755e1fbd80b0346aefd0e75dc42d9d22765151bdbec651871
https://api.icon.community/api/v3d
POST 404 error
response: rpc_debug is false

**Comment by robcxyz** [comment]
Ah I think I know what it is. Need to enable that. Not every request fails so it is based on the load balancer. Will update thanks. Will close this when done.

**Comment by VagPanour** [comment]
Ok cool!
