### ISSUE TITLE
Adding functionality to apply network proposals

### ISSUE THREAD

**Issue by FidelVe** [sudoblockio/icon-tracker-frontend#304]
Once a network proposal has reached the required conditions to be approved, a transaction to apply the proposal is needed

https://github.com/icon-project/governance2#applyproposal

The tracker should show a button on each non-expired proposal to apply them to the chain

**Comment by robcxyz** [comment]
Keeping this open until we validate it with the next proposal.

**Comment by FidelVe** [comment]
this can be closed it was tested by Ibriz during the last proposal and it worked
