### ISSUE TITLE
Transactions tab the same as token transfers tab in token detail view 

### ISSUE THREAD

**Issue by robcxyz** [sudoblockio/icon-tracker-frontend#327]
http://localhost:3000/token/cx9ab3078e72c8d9017194d17b34b1a47b661945ca

Clicking back and forth doesn't help

**Comment by FidelVe** [comment]
Taking a look at this issue.

When running the tracker locally and going into the `/token/cx...234` route of a token contract you can see a `Transaction` and a `Token transfer` tab as shown in the following screenshot
![Screenshot from 2023-09-28 17-46-03](https://github.com/sudoblockio/icon-tracker-frontend/assets/43641727/eff3d146-ed69-4100-977c-54b361b910d1)

If you go into the current live version of the tracker and visit the page of a token you will only see a `Token transfer` tab


![Screenshot from 2023-09-28 17-47-27](https://github.com/sudoblockio/icon-tracker-frontend/assets/43641727/0cf79c53-7127-42a5-b2b9-fd8afece1a3c)

I think that the correct display is what you can see in the live version, not whatever is happening in the current version of the `cra5-update` for the Token page there should only be a `Token Transfer` tab.

Checking at the code this new tab (the `Transaction` Tab for the Token page) it seems that it was something that was introduced by mistake, you can check the diff here (look for the `src/components/TokensPage/TokenDetailPage/TokenTabs/index.js` file)

https://github.com/sudoblockio/icon-tracker-frontend/compare/main...cra5-update

Here is the the source code on the main branch
https://github.com/sudoblockio/icon-tracker-frontend/blob/main/src/components/TokensPage/TokenDetailPage/TokenTabs/index.js#L41

here is the source code on the cra5-update branch
https://github.com/sudoblockio/icon-tracker-frontend/blob/cra5-update/src/components/TokensPage/TokenDetailPage/TokenTabs/index.js#L63

the solution would be to remove either the `case 0` or `case 1` in that switch, they are both the same.

Let me know your opinion on it.
