### ISSUE TITLE
Bug-Pagination Issue

### ISSUE THREAD

**Issue by VagPanour** [sudoblockio/icon-tracker-frontend#335]
After expanding transactions of a wallet, hitting the button for the next page doesn't work. There is no issue manually doing from url. If you just type the page number in the box, it creates the url but not redirecting unless you refresh the whole page. Issue happened recently. Not sure if its on my end only.

**Comment by robcxyz** [comment]
@Aviraj-Singh - Indeed this is an issue.

As you can see in this page you can not go to the next page.

**Comment by robcxyz** [comment]
Fixed and released
