### ISSUE TITLE
Proposal vote step limit

### ISSUE THREAD

**Issue by CyrusVorwald** [sudoblockio/icon-tracker-frontend#336]
Currently, when voting on proposals, the frontend doesn't automatically increase the step limit, so with Hana it always fails, because u can't adjust the step limit in that wallet. And with ICONex, you need to know to increase the step limit to get it to work.

There should be a way to adjust the step limit or automatically increase it to what is needed for a transaction to execute.

**Comment by robcxyz** [comment]
@CyrusVorwald - There is no way to automatically update it based on the proposal but we can give it a sufficiently large number to allow for any proposal to be voted on. Issue is some proposals are larger than others so I think this works for smaller ones but could be mistaken.  We'll update this on the next vote.

**Comment by robcxyz** [comment]
@FidelVe - Line is here 

@FidelVe - This is the line we need to update but no

**Comment by FidelVe** [comment]
these are the types of issues that if I was able to test with mock proposals on a testnet I would be able to figure out a proper solution 😅

@robcxyz like we talked on telegram ill simply add a zero to this
