### ISSUE TITLE
Estimate step for contract calls on Tracker

### ISSUE THREAD

**Issue by AntonAndell** [sudoblockio/icon-tracker-frontend#409]
Currently calling contracts in tracker uses a fixed step limit of 2000000 which is to small for most interactions. Id suggest adding a step that estimated the fee of the call prior to sending to Hana. Or just setting it to the max value of 2500000000.
If using Hana it will still display the estimated cost for users before the confirm so this solution will most likely be sufficient for most users.  

https://github.com/sudoblockio/icon-tracker-frontend/blob/e7758c48cad32da35fd113c91a9f9a860d61c0ed/src/utils/rawTxMaker/api/helpers.js#L27

**Comment by robcxyz** [comment]
@AntonAndell - Is there a tool we can use to estimate the step?

Otherwise can change the default value to max but for those with only a few ICX in their wallet they'll run into issues right?

**Comment by AntonAndell** [comment]
Yeah there should be a rpc call to send a transaction for estimation which would be the optimal solution

**Comment by AntonAndell** [comment]
https://github.com/icon-project/goloop/blob/master/doc/jsonrpc_v3.md#debug_estimatestep

**Comment by robcxyz** [comment]
https://docs.icon.community/develop-on-icon-chain/smart-contracts/how-to-write-a-smart-contract/how-to-estimate-required-step
