### ISSUE TITLE
Change % of bond calculation

### ISSUE THREAD

**Issue by nightowl121** [sudoblockio/icon-tracker-frontend#444]
The current bond % calculation is not correct.
For example:
<img width="1160" alt="image" src="https://github.com/sudoblockio/icon-tracker-frontend/assets/91905208/e2eaca05-afc2-442a-831d-e721eedaec5b">

Here sudoblock bond % is greater than 100% but there is still room for additional bond. A number greater than or equal to 100% would mean that there is sufficient bond for the total votes. In case of sudoblock it is not the case.

If the calculation is changed to the following formula it would be correct:
**Bond % = (bond * 20)/(bond + total votes)**

For sudoblock,
Bond % = (420,000 * 20)/(420,000 + 8,291,036)
               = 96.43%
 So additional bond required would be = (8,291,036/19)-420,000 = 16,370.32
 
 Thus if bond would have been equal to **votes/19**(8,291,036/19) = 436,370.32, the bond % would be 100.
 Bond % = (436,370.32*20)/(436,370.32+8,291,036) = 100%
 
 So this way of calculation would also solve infinity% error. The maximum % you would get is (x*20/x+0) = 2,000%

**Comment by FidelVe** [comment]
A validator power or "voting power" is done via the following eequation:

```
validatorDelegatedAmount = Amount that is being delegated by the general voters
validatorBondingAmount = Amount that is being bonded by the validator
validatorVotingAmount = validatorDelegatedAmount + validatorBondingAmount

validatorPower = min(validatorVotingAmount, validatorBonding * 20)
```

Using sudoblock current values for the validator:

```
{
  "bonded": "0x58f03ee118a13e800000", // 8306651.000222631
  "delegated": "0x6df0073f9834708cafe8d", // 420000
  "power": "0x6f2c4e995ec98e2000000", // 8400000
  ...
}
```

Applying the power formula:

```
validatorDelegatedAmount = 8306651.000222631
validatorBondingAmount = 420000
validatorVotingAmount = 8726651.00022263

validatorPower = min(8726651.00022263, 8400000) = 8400000
```

Following with the logic of the equation if sudoblock receives more delegation the power will NOT increase and to fully use the current delegations the bonding should increase by 16332.55 to a total of 436332.55, which means that @nightowl121 is correct in the assesment that the current calculation is wrong or is just showing something else.

**Comment by FidelVe** [comment]
@robcxyz

this changes should not have an impact in the reward calculation if we are using the voting power value that comes directly from the rpc request of `getPreps`

if the tracker is not using the power value that comes from that rpc call directly and instead is calculating again the power then it will impact the reward calculation

**Comment by robcxyz** [comment]
Ok so `Bond % = (bond * 20)/(bond + total votes)` is it. Power comes from contract, not calculating that, but it now makes sense considering the formula (power for sudoblock should be lower if not)... 

Also rewards calcs come to think of it won't change. They are all based on power which comes from chain. 

Will fix now.
