### ISSUE TITLE
"Governance" section on tracker.icon.community pulling incorrect data for CPS participants

### ISSUE THREAD

**Issue by tjhunt1** [sudoblockio/icon-tracker-frontend#59]
Should be 27 P-Reps w/ a check mark for participating in CPS Governance (according to CPS smart contracts), but I'm only counting 20 P-Reps displayed on the community tracker.

<img width="158" alt="Screen Shot 2022-08-01 at 12 32 44 PM" src="https://user-images.githubusercontent.com/98855020/182208381-881828bd-c28d-4325-849e-70960dfcd669.png">

**Comment by tjhunt1** [comment]
you should be able to pull the information from the "get_PReps" method on the cps_score smart contract

https://tracker.icon.community/contract/cx9f4ab72f854d3ccdc59aa6f2c3e2215dd62e879f#readcontract

**Comment by robcxyz** [comment]
Fixed and released in [v0.1.7](https://github.com/sudoblockio/icon-tracker-frontend/releases/tag/v0.1.7)
