### ISSUE TITLE
Add QR code to addresses

### ISSUE THREAD

**Issue by CyrusVorwald-ICON** [sudoblockio/icon-tracker-frontend#62]
Addresses have qr codes in the tracker.icon.foundation service. It should be the same for tracker.icon.community.

For example:

![image](https://user-images.githubusercontent.com/90732384/183492324-72b91424-64e2-4ec6-a7d2-9c6db60b1f01.png)

https://tracker.icon.foundation/address/hx562dc1e2c7897432c298115bc7fbcc3b9d5df294 has a qr code

https://tracker.icon.community/address/hx562dc1e2c7897432c298115bc7fbcc3b9d5df294 does not have a qr code

**Comment by robcxyz** [comment]
Should look like this -> https://tracker.icon.foundation/address/hx562dc1e2c7897432c298115bc7fbcc3b9d5df294
