### ISSUE TITLE
Tracker does not show contract that were deployed by another contract properly.

### ISSUE THREAD

**Issue by izyak** [sudoblockio/icon-tracker-frontend#63]
When a contract is deployed by another contract, the tracker cannot pick up deployed contract properly.
Contract creator, name, all readonly methods in contract, cannot be seen in the tracker.
[Sample Contract](https://tracker.icon.community/contract/cx93630377792703074042c45eac976d9672ede367#code)

Detailed description from icon bridge repo:
https://github.com/icon-project/icon-bridge/issues/27#issuecomment-1197637148

**Comment by bbist** [comment]
Hi @robcxyz,
Would it be possible to prioritize this issue?

**Comment by robcxyz** [comment]
Since there is more info in https://github.com/icon-project/icon-bridge/issues/27, lets keep the discussion over there.  I'll need some additional info on this contract I think as the creation events are getting missed.
