### ISSUE TITLE
"Transfers" & "Holders" bug for token contract

### ISSUE THREAD

**Issue by tjhunt1** [sudoblockio/icon-tracker-frontend#65]
This issue is occurring for the Jungle Jackpot Token (JJT) and has been replicated across other tokens (CDT2, etc).

[On the Foundation Tracker, JJT displays 5 transfers and 4 token holders:](https://tracker.icon.foundation/token/cx08bb2e689af60bbf0ae4eeb1b2a63e75737eb94d#tokenholders)
![Screen Shot 2022-08-23 at 1 55 26 PM](https://user-images.githubusercontent.com/98855020/186240748-40e0078f-3133-4fe1-b09b-f6d3196e8226.png)

[On the Community Tracker, JJT displays -1 transfers and 6 token holders:](https://tracker.icon.community/token/cx08bb2e689af60bbf0ae4eeb1b2a63e75737eb94d#tokenholders)
![Screen Shot 2022-08-23 at 1 55 55 PM](https://user-images.githubusercontent.com/98855020/186240822-6e18cc4b-3756-4d17-b733-6df97db5e55b.png)

**Comment by robcxyz** [comment]
This was very likely interim as I had a backup tracker going at that time and I am not seeing it on the main tracker right now.
