### ISSUE TITLE
Community Tracker does not display Token Symbols

### ISSUE THREAD

**Issue by tjhunt1** [sudoblockio/icon-tracker-frontend#66]
[Tokens tab](https://tracker.icon.community/tokens/1?count=25)

![Screen Shot 2022-08-23 at 1 56 43 PM](https://user-images.githubusercontent.com/98855020/186240967-685f819b-6af7-4471-88c8-305b1169e72a.png)

**Comment by robcxyz** [comment]
This is being worked on and will come up in the next sync.

**Comment by robcxyz** [comment]
Needs to get deployed in other cluster but right now it is working in dev env. Opening issue in transformer to account for a couple addresses that aren't showing as they seem to be not have any Txs and hence are missing the point of indexing.
