### ISSUE TITLE
Ranking information unavailable beyond top 25 for IRC-2 tokens other than ICX

### ISSUE THREAD

**Issue by elsishin** [sudoblockio/icon-tracker-frontend#67]
### Issue type 

- [X ] Bug 
- [ ] Feature request

### Issue Description

Tracker doesn't seem to be able to show ranking information beyond the top 25 holders for IRC-2 tokens other than ICX. 
E.g., you can only see up to top 25 holders for BALN: https://tracker.icon.community/token/cxf61cd5a45dc9f91c15aa65831a30a90d59a09619#tokenholders

### Steps to Reproduce the Problem / Desired Outcome 

  1. Show ranking information beyond top 25.

**Comment by robcxyz** [comment]
@elsishin - I am looking at this now and I think what is broken is the holders list view which you get by clicking on the total holders, not in the page linked. That being said, the pagination is broken there so it needs to be fixed.

**Comment by robcxyz** [comment]
@elsishin - I am looking at this now and I think what is broken is the holders list view which you get by clicking on the total holders, not in the page linked. That being said, the pagination is broken there so it needs to be fixed.

**Comment by robcxyz** [comment]
Similar to https://github.com/sudoblockio/icon-tracker-frontend/pull/47

**Comment by robcxyz** [comment]
http://localhost:3000/tokenholders/cx9ab3078e72c8d9017194d17b34b1a47b661945ca/1?count=100
