### ISSUE TITLE
"btp-0x61.bsc-BNB" token name displayed as "undefined" on lisbon tracker

### ISSUE THREAD

**Issue by FidelVe** [sudoblockio/icon-tracker-frontend#74]
In the `Balance` section of a wallet address the `btp-0x61.bsc-BNB` token name is being displayed as `undefined` here is a screenshot and the wallet address link
![Screenshot from 2022-10-20 15-09-15](https://user-images.githubusercontent.com/43641727/197037804-c16864b8-0f40-4c44-aeb6-46913ea1005d.png)

https://tracker.lisbon.icon.community/address/hx0169e03001a3fa4012092ad4a4ddf2d07681f063#tokentransfers

**Comment by robcxyz** [comment]
Thanks for reporting. This is fixed now.
