### ISSUE TITLE
[feature request] add a 'method' column in the transaction table

### ISSUE THREAD

**Issue by FidelVe** [sudoblockio/icon-tracker-frontend#88]
Hi team.

sorry if this is not the place for this post since this is not an issue but I would like to make a feature request.

I think it would be very useful to have a `method` column in the transaction table like is showing in this example for the BSC tracker
![Screenshot from 2022-11-25 14-19-53](https://user-images.githubusercontent.com/43641727/204039206-8fd4edb9-ec3f-4539-850b-c4a338cb7cf6.png)

here is ICON tracker for comparison
![Screenshot from 2022-11-25 14-20-10](https://user-images.githubusercontent.com/43641727/204039274-73f673a2-9516-4b68-8992-3bab1b38d977.png)

this 'method' column makes it very easy to navigate the transfers when developing an app that interacts with a smart contract.

**Comment by robcxyz** [comment]
@FidelVe - Yeah that sounds reasonable. Will get that in this sprint.

**Comment by robcxyz** [comment]
In this table to 

https://tracker.v2.mainnet.sng.vultr.icon.community/contracttx/cx087b4164a87fdfb7b714f3bafe9dfb050fd6b132
