### ISSUE TITLE
Community is missing a lot of tabs for Prep wallets

### ISSUE THREAD

**Issue by Geograd** [sudoblockio/icon-tracker-frontend#91]
Community page:
https://tracker.icon.community/address/hx9121c5914ce34f59de52fe15efd6f7982c2ab8ae

Solidwallet page:
https://main.tracker.solidwallet.io/address/hx9121c5914ce34f59de52fe15efd6f7982c2ab8ae

Community page is missing Internal tx, Token Transfers, Voters, Bonders, and Rewards

**Comment by robcxyz** [comment]
Related to https://github.com/sudoblockio/icon-go-api/issues/14

**Comment by robcxyz** [comment]
Fixed
